let home = document.querySelector('.home')
let user = document.querySelector('.user')
let transaction = document.querySelector('.transaction')
let withdraw = document.querySelector('.withdraw')
let crypto = document.querySelector('.crypto')
let giftCard = document.querySelector('.gift-card')
let funds = document.querySelector('.funds')
let dashboard = document.querySelector('.details')
let withdrawa = document.querySelector('.WITHDRAWA')
let cryptocurrencies = document.querySelector('.cryptocurrencies')
let userDetails = document.querySelector('.user-details')
let cryptoDetails = document.querySelector('.crypto-details')
let userInfo = document.querySelector('.user-info')
let coinType = document.querySelector('.coin-type')
let selectCoin = document.querySelector('.select-coin')
let fundsss = document.querySelector('.fundsss')
let bit = document.querySelector('.bit')
let bitCoin = document.querySelector('.bit-coin')
let barBitImage = document.querySelector('.bitcoin-icon')
let addCrypto = document.getElementById('add-crypto')
let addInfo = document.querySelector('.add-info')
let edit = document.querySelector('.edit')

home.addEventListener('click', function(){
    home.classList.add('selected')
    user.classList.remove('selected')
    transaction.classList.remove('selected')
    withdraw.classList.remove('selected')
    crypto.classList.remove('selected')
    funds.classList.remove('selected')
    giftCard.classList.remove('selected')
    dashboard.classList.remove('hide')
    cryptoDetails.classList.add('hide')
    cryptocurrencies.classList.add('hide')
    withdrawa.classList.add('hide')
    userDetails.classList.add('hide')
    fundsss.classList.add('hide')

})
user.addEventListener('click', function(){
    user.classList.add('selected')
    home.classList.remove('selected')
    transaction.classList.remove('selected')
    withdraw.classList.remove('selected')
    crypto.classList.remove('selected')
    funds.classList.remove('selected')
    giftCard.classList.remove('selected')
    dashboard.classList.add('hide')
    withdrawa.classList.add('hide')
    userDetails.classList.remove('hide')
    cryptoDetails.classList.add('hide')
    cryptocurrencies.classList.add('hide')
    fundsss.classList.add('hide')
    
})

addInfo.addEventListener('click', function(){
    userDetails.classList.add('hide')
    userInfo.classList.remove('hide')
    
})

withdraw.addEventListener('click', function(){
    user.classList.remove('selected')
    home.classList.remove('selected')
    transaction.classList.remove('selected')
    withdraw.classList.add('selected')
    crypto.classList.remove('selected')
    funds.classList.remove('selected')
    giftCard.classList.remove('selected')
    dashboard.classList.add('hide')
    withdrawa.classList.remove('hide')
    userDetails.classList.add('hide')
    fundsss.classList.add('hide')
    cryptoDetails.classList.add('hide')
    cryptocurrencies.classList.add('hide')

})
crypto.addEventListener('click', function(){
    home.classList.remove('selected')
    user.classList.remove('selected')
    transaction.classList.remove('selected')
    withdraw.classList.remove('selected')
    crypto.classList.add('selected')
    funds.classList.remove('selected')
    giftCard.classList.remove('selected')
    dashboard.classList.add('hide')
    withdrawa.classList.add('hide')
    userDetails.classList.add('hide')
    cryptoDetails.classList.remove('hide')
    cryptocurrencies.classList.remove('hide')
    fundsss.classList.add('hide')
    
})
coinType.addEventListener('click', function(){
    dashboard.classList.add('hide')
    withdrawa.classList.add('hide')
    selectCoin.classList.remove('hide')
    cryptoDetails.classList.add('hide')
    userDetails.classList.add('hide')
    fundsss.classList.add('hide')

})

funds.addEventListener('click', function(){
    home.classList.remove('selected')
    user.classList.remove('selected')
    transaction.classList.remove('selected')
    withdraw.classList.remove('selected')
    crypto.classList.remove('selected')
    funds.classList.add('selected')
    giftCard.classList.remove('selected')
    dashboard.classList.add('hide')
    withdrawa.classList.add('hide')
    userDetails.classList.add('hide')
    cryptoDetails.classList.remove('hide')
    fundsss.classList.remove('hide')
    cryptocurrencies.classList.add('hide')
    
})

bit.addEventListener('click', function(){
   bit.classList.toggle('bit-design')
})

addCrypto.addEventListener('click', function(){
    if(bit.classList.contains('bit-design')){
        selectCoin.classList.add('hide')
        coinType.classList.add('hide')
        cryptoDetails.classList.remove('hide')
        bitCoin.classList.remove('hide')
        barBitImage.classList.remove('hide')
        edit.classList.remove('hidden')
    }

})